export type Category = "crypto" | "commodities" | "stocks" | "indices" | "forex" | "pre-ipo";

export interface Market {
  id: string;
  name: string;
  pair: string;
  price: number;
  change24h: number;
  abbr: string;
  color: string;
  category: Category;
  type: "5min" | "15min" | "1h" | "daily" | "perp";
  typeLabel: string;
  description: string;
  rules: string;
  sparkline: number[];
  currency: string;
  upOdds: number;
  downOdds: number;
}

export const categoryLabels: Record<Category, string> = {
  crypto: "Krypto",
  commodities: "Rohstoffe",
  stocks: "Aktien",
  indices: "Indizes",
  forex: "Forex",
  "pre-ipo": "Pre-IPO",
};

function generateSparkline(base: number, volatility: number, points = 48): number[] {
  const data: number[] = [];
  let current = base;
  for (let i = 0; i < points; i++) {
    current += (Math.random() - 0.48) * volatility;
    data.push(current);
  }
  return data;
}

function odds(): { upOdds: number; downOdds: number } {
  const up = Math.floor(Math.random() * 60) + 20;
  return { upOdds: up, downOdds: 100 - up };
}

export const markets: Market[] = [
  // ── Crypto ──
  {
    id: "btc-5min",
    name: "Bitcoin",
    pair: "BTC/USD",
    price: 84800,
    change24h: 2.3,
    abbr: "BTC",
    color: "#f7931a",
    category: "crypto",
    type: "5min",
    typeLabel: "5 Min",
    description: "Geht Bitcoin in den nächsten 5 Minuten hoch oder runter? Setze auf die kurzfristige Preisbewegung.",
    rules: "Der Markt wird zum aktuellen BTC/USD Spot-Preis eröffnet. Nach 5 Minuten wird der Schlusskurs ermittelt. Liegt der Schlusskurs über dem Eröffnungskurs, gewinnt 'Hoch'. Liegt er darunter, gewinnt 'Runter'.",
    sparkline: generateSparkline(84800, 400),
    currency: "$",
    ...odds(),
  },
  {
    id: "btc-15min",
    name: "Bitcoin",
    pair: "BTC/USD",
    price: 84800,
    change24h: 2.3,
    abbr: "BTC",
    color: "#f7931a",
    category: "crypto",
    type: "15min",
    typeLabel: "15 Min",
    description: "Steigt oder fällt Bitcoin in den nächsten 15 Minuten?",
    rules: "Markt basiert auf dem BTC/USD Spot-Preis. 15-Minuten-Fenster mit festem Eröffnungs- und Schlusskurs.",
    sparkline: generateSparkline(84800, 600),
    currency: "$",
    ...odds(),
  },
  {
    id: "eth-15min",
    name: "Ethereum",
    pair: "ETH/USD",
    price: 1620,
    change24h: 1.8,
    abbr: "ETH",
    color: "#627eea",
    category: "crypto",
    type: "15min",
    typeLabel: "15 Min",
    description: "Ethereum 15-Minuten-Markt. Sage die kurzfristige Richtung vorher.",
    rules: "Basiert auf dem ETH/USD Spot-Preis. Alle 15 Minuten wird ein neuer Markt eröffnet.",
    sparkline: generateSparkline(1620, 15),
    currency: "$",
    ...odds(),
  },
  {
    id: "sol-5min",
    name: "Solana",
    pair: "SOL/USD",
    price: 148.5,
    change24h: 4.1,
    abbr: "SOL",
    color: "#9945ff",
    category: "crypto",
    type: "5min",
    typeLabel: "5 Min",
    description: "Solana 5-Minuten-Sprint. Schnelle Märkte für schnelle Entscheidungen.",
    rules: "SOL/USD Spot-Preis. 5-Minuten-Fenster.",
    sparkline: generateSparkline(148.5, 3),
    currency: "$",
    ...odds(),
  },
  {
    id: "xrp-1h",
    name: "XRP",
    pair: "XRP/USD",
    price: 2.18,
    change24h: -1.2,
    abbr: "XRP",
    color: "#00aae4",
    category: "crypto",
    type: "1h",
    typeLabel: "1 Std",
    description: "Wohin bewegt sich XRP in der nächsten Stunde?",
    rules: "XRP/USD Spot-Preis. 1-Stunden-Fenster.",
    sparkline: generateSparkline(2.18, 0.05),
    currency: "$",
    ...odds(),
  },

  // ── Commodities ──
  {
    id: "gold-15min",
    name: "Gold",
    pair: "XAU/USD",
    price: 3340,
    change24h: 0.5,
    abbr: "XAU",
    color: "#ffd700",
    category: "commodities",
    type: "15min",
    typeLabel: "15 Min",
    description: "Gold 15-Minuten-Markt. Trade den sicheren Hafen in Echtzeit.",
    rules: "XAU/USD Spot-Preis. 15-Minuten-Intervalle.",
    sparkline: generateSparkline(3340, 10),
    currency: "$",
    ...odds(),
  },
  {
    id: "oil-15min",
    name: "Öl (WTI)",
    pair: "OIL/USD",
    price: 64.5,
    change24h: -1.2,
    abbr: "OIL",
    color: "#1a1a1a",
    category: "commodities",
    type: "15min",
    typeLabel: "15 Min",
    description: "WTI Rohöl 15-Minuten-Markt. OPEC-Entscheidungen bewegen den Preis.",
    rules: "WTI Crude Oil Spot-Preis. 15-Minuten-Fenster.",
    sparkline: generateSparkline(64.5, 0.5),
    currency: "$",
    ...odds(),
  },
  {
    id: "silver-1h",
    name: "Silber",
    pair: "XAG/USD",
    price: 32.8,
    change24h: 1.1,
    abbr: "XAG",
    color: "#c0c0c0",
    category: "commodities",
    type: "1h",
    typeLabel: "1 Std",
    description: "Silber Stunden-Markt. Industriemetall mit Momentum.",
    rules: "XAG/USD Spot-Preis. 1-Stunden-Intervalle.",
    sparkline: generateSparkline(32.8, 0.3),
    currency: "$",
    ...odds(),
  },
  {
    id: "natgas-daily",
    name: "Erdgas",
    pair: "NG/USD",
    price: 3.42,
    change24h: -2.8,
    abbr: "NG",
    color: "#ff6b35",
    category: "commodities",
    type: "daily",
    typeLabel: "Tages",
    description: "Erdgas Tagesmarkt. Volatil und wetterabhängig.",
    rules: "Natural Gas Futures Preis. Tägliches Settlement.",
    sparkline: generateSparkline(3.42, 0.08),
    currency: "$",
    ...odds(),
  },

  // ── Stocks ──
  {
    id: "nvda-15min",
    name: "NVIDIA",
    pair: "NVDA",
    price: 110,
    change24h: 3.1,
    abbr: "NVDA",
    color: "#76b900",
    category: "stocks",
    type: "15min",
    typeLabel: "15 Min",
    description: "NVIDIA 15-Minuten-Markt. Der AI-Chip-Gigant in Echtzeit.",
    rules: "NVDA Aktienkurs. 15-Minuten-Fenster während der Handelszeiten.",
    sparkline: generateSparkline(110, 2),
    currency: "$",
    ...odds(),
  },
  {
    id: "tsla-5min",
    name: "Tesla",
    pair: "TSLA",
    price: 240,
    change24h: -0.8,
    abbr: "TSLA",
    color: "#cc0000",
    category: "stocks",
    type: "5min",
    typeLabel: "5 Min",
    description: "Tesla 5-Minuten-Sprint. Musk-getriebene Volatilität.",
    rules: "TSLA Aktienkurs. 5-Minuten-Fenster.",
    sparkline: generateSparkline(240, 3),
    currency: "$",
    ...odds(),
  },
  {
    id: "aapl-1h",
    name: "Apple",
    pair: "AAPL",
    price: 198.5,
    change24h: 0.4,
    abbr: "AAPL",
    color: "#555555",
    category: "stocks",
    type: "1h",
    typeLabel: "1 Std",
    description: "Apple Stunden-Markt. Der wertvollste Konzern der Welt.",
    rules: "AAPL Aktienkurs. 1-Stunden-Fenster.",
    sparkline: generateSparkline(198.5, 1.5),
    currency: "$",
    ...odds(),
  },
  {
    id: "meta-15min",
    name: "Meta",
    pair: "META",
    price: 512,
    change24h: 1.9,
    abbr: "META",
    color: "#0668e1",
    category: "stocks",
    type: "15min",
    typeLabel: "15 Min",
    description: "Meta Platforms 15-Minuten-Markt.",
    rules: "META Aktienkurs. 15-Minuten-Fenster.",
    sparkline: generateSparkline(512, 5),
    currency: "$",
    ...odds(),
  },
  {
    id: "amzn-1h",
    name: "Amazon",
    pair: "AMZN",
    price: 186.3,
    change24h: 0.7,
    abbr: "AMZN",
    color: "#ff9900",
    category: "stocks",
    type: "1h",
    typeLabel: "1 Std",
    description: "Amazon Stunden-Markt. E-Commerce und Cloud in einem Trade.",
    rules: "AMZN Aktienkurs. 1-Stunden-Fenster.",
    sparkline: generateSparkline(186.3, 1.8),
    currency: "$",
    ...odds(),
  },

  // ── Indices ──
  {
    id: "sp500-15min",
    name: "S&P 500",
    pair: "SPX",
    price: 5280,
    change24h: 0.8,
    abbr: "SPX",
    color: "#e8363a",
    category: "indices",
    type: "15min",
    typeLabel: "15 Min",
    description: "S&P 500 15-Minuten-Markt. Der wichtigste Index der Welt.",
    rules: "S&P 500 Index. 15-Minuten-Fenster.",
    sparkline: generateSparkline(5280, 20),
    currency: "$",
    ...odds(),
  },
  {
    id: "dax-15min",
    name: "DAX",
    pair: "DAX",
    price: 21205,
    change24h: 1.2,
    abbr: "DAX",
    color: "#003399",
    category: "indices",
    type: "15min",
    typeLabel: "15 Min",
    description: "DAX 15-Minuten-Markt. Deutschlands Leitindex.",
    rules: "DAX 40 Index. 15-Minuten-Fenster.",
    sparkline: generateSparkline(21205, 80),
    currency: "€",
    ...odds(),
  },
  {
    id: "nasdaq-5min",
    name: "Nasdaq 100",
    pair: "NDX",
    price: 18340,
    change24h: 1.5,
    abbr: "NDX",
    color: "#0097d1",
    category: "indices",
    type: "5min",
    typeLabel: "5 Min",
    description: "Nasdaq 100 5-Minuten-Sprint. Tech-Index mit Momentum.",
    rules: "Nasdaq 100 Index. 5-Minuten-Fenster.",
    sparkline: generateSparkline(18340, 60),
    currency: "$",
    ...odds(),
  },

  // ── Forex ──
  {
    id: "eurusd-5min",
    name: "EUR/USD",
    pair: "EUR/USD",
    price: 1.1365,
    change24h: 0.3,
    abbr: "EU",
    color: "#003399",
    category: "forex",
    type: "5min",
    typeLabel: "5 Min",
    description: "Euro gegen US-Dollar. Das meistgehandelte Währungspaar der Welt.",
    rules: "EUR/USD Spot-Kurs. 5-Minuten-Fenster.",
    sparkline: generateSparkline(1.1365, 0.002),
    currency: "",
    ...odds(),
  },
  {
    id: "gbpusd-15min",
    name: "GBP/USD",
    pair: "GBP/USD",
    price: 1.3285,
    change24h: -0.2,
    abbr: "GU",
    color: "#cf142b",
    category: "forex",
    type: "15min",
    typeLabel: "15 Min",
    description: "Britisches Pfund gegen US-Dollar.",
    rules: "GBP/USD Spot-Kurs. 15-Minuten-Fenster.",
    sparkline: generateSparkline(1.3285, 0.003),
    currency: "",
    ...odds(),
  },
  {
    id: "usdjpy-1h",
    name: "USD/JPY",
    pair: "USD/JPY",
    price: 142.35,
    change24h: -0.5,
    abbr: "UJ",
    color: "#bc002d",
    category: "forex",
    type: "1h",
    typeLabel: "1 Std",
    description: "US-Dollar gegen Japanischen Yen.",
    rules: "USD/JPY Spot-Kurs. 1-Stunden-Fenster.",
    sparkline: generateSparkline(142.35, 0.3),
    currency: "",
    ...odds(),
  },

  // ── Pre-IPO ──
  {
    id: "anthropic-daily",
    name: "Anthropic",
    pair: "ANTH",
    price: 45.0,
    change24h: 5.2,
    abbr: "ANTH",
    color: "#d4a574",
    category: "pre-ipo",
    type: "daily",
    typeLabel: "Tages",
    description: "Anthropic Pre-IPO Markt. Wette auf die Bewertung des Claude-Herstellers.",
    rules: "Basiert auf der impliziten Bewertung aus Sekundärmarkt-Transaktionen. Tägliches Settlement.",
    sparkline: generateSparkline(45, 1),
    currency: "$",
    ...odds(),
  },
  {
    id: "spacex-daily",
    name: "SpaceX",
    pair: "SPCX",
    price: 185.0,
    change24h: 2.1,
    abbr: "SPCX",
    color: "#005288",
    category: "pre-ipo",
    type: "daily",
    typeLabel: "Tages",
    description: "SpaceX Pre-IPO Markt. Starship, Starlink und die Zukunft der Raumfahrt.",
    rules: "Implizierte Bewertung aus Sekundärmarkt. Tägliches Settlement.",
    sparkline: generateSparkline(185, 4),
    currency: "$",
    ...odds(),
  },
  {
    id: "stripe-daily",
    name: "Stripe",
    pair: "STRP",
    price: 72.0,
    change24h: 0.8,
    abbr: "STRP",
    color: "#635bff",
    category: "pre-ipo",
    type: "daily",
    typeLabel: "Tages",
    description: "Stripe Pre-IPO Markt. Der Payment-Gigant vor dem Börsengang.",
    rules: "Implizierte Bewertung aus Sekundärmarkt. Tägliches Settlement.",
    sparkline: generateSparkline(72, 1.5),
    currency: "$",
    ...odds(),
  },
];

export function getMarketsByCategory(category: Category): Market[] {
  return markets.filter((m) => m.category === category);
}

export function getRelatedMarkets(market: Market, limit = 4): Market[] {
  return markets
    .filter((m) => m.category === market.category && m.id !== market.id)
    .slice(0, limit);
}

export function getMarketById(id: string): Market | undefined {
  return markets.find((m) => m.id === id);
}
