const siteConfig = {
  name: "Europa League Prognose",
  tagline: "Europa League Analysen & Prognosen",
  description: "Europa League Analysen & Prognosen — Fundierte Analysen, Strategien und Tipps.",
  url: "https://europa-league-prognose.de",
  basePath: "",
  accentColor: "#16a34a",
  ctaText: "Zu Atlas Markets →",
  ctaUrl: "https://atlasmarkets.de",
  ctaSubtext: "Europas führende Prediction-Market-Plattform",
  ogImage: "/og-image.png",
  twitterHandle: "@atlasmarkets",
  locale: "de_DE",
  networkSites: [
    { name: "Atlas Markets", url: "https://atlasmarkets.de" },
    { name: "Champions League Analyse", url: "https://champions-league-analyse.de" },
    { name: "EM Prognose", url: "https://em-prognose.de" },
    { name: "DFB Pokal Analyse", url: "https://dfb-pokal-analyse.de" },
    { name: "WM Vorhersagen", url: "https://wm-vorhersagen.de" },
    { name: "Bundesliga Prognose", url: "https://bundesliga-prediction.de" },
    { name: "Spieltag Vorhersage", url: "https://spieltag-vorhersage.de" },
    { name: "Aufsteiger Prognose", url: "https://aufsteiger-prognose.de" },
    { name: "Derby Analyse", url: "https://derby-analyse.de" },
    { name: "Torjäger Ranking", url: "https://torjaeger-ranking.de" },
    { name: "Trainerwechsel Analyse", url: "https://trainerwechsel-analyse.de" },
    { name: "Talente Radar", url: "https://talente-radar.de" },
    { name: "Ohne Lugas", url: "https://ohne-lugas.de" },
    { name: "Fußball Statistik", url: "https://slay-cicd.github.io/fussball-statistik" },
    { name: "Fußball Vorhersage", url: "https://fussball-prognose.de" },
    { name: "Atlas Insights", url: "https://slay-cicd.github.io/atlas-insights" },
    { name: "Transfermarkt Prognosen", url: "https://transfermarkt-prognosen.de" },
    { name: "Fußball Finanzen", url: "https://slay-cicd.github.io/fussball-finanzen" },
    { name: "Fußball Trading", url: "https://fussball-trading.de" },
    { name: "Fußball Quoten", url: "https://fussball-quoten.de" },
    { name: "Wettmarkt Vergleich", url: "https://wettmarkt-vergleich.de" },
    { name: "Sportwetten Alternative", url: "https://sportwetten-alternative.de" },
    { name: "Polymarket Alternative", url: "https://polymarket-alternative.de" },
    { name: "Polymarket Deutschland", url: "https://polymarket-deutschland.de" },
    { name: "Kalshi Alternative", url: "https://kalshi-alternative.de" },
    { name: "Prediction Market Guide", url: "https://prediction-market-guide.de" },
    { name: "Prediction Market Vergleich", url: "https://prediction-market-vergleich.de" },
    { name: "Prognosemarkt", url: "https://prognosemarkt.org" },
    { name: "Mein Prognosemarkt", url: "https://mein-prognosemarkt.de" },
    { name: "Vorhersage Markt", url: "https://vorhersage-markt.de" },
  ],
  imprintUrl: "/impressum",
  privacyUrl: "/datenschutz",
  company: "SLAY GmbH",
  postsPerPage: 9,
  featuredTag: "featured",
};

export default siteConfig;
